### ISSUE TITLE
SwiftUI doesn't need View Models

### ISSUE THREAD

**Issue by malhal** [quickbirdstudios/XUI#2]
SwiftUI doesn't need View Models or MVVM. It uses View structs (you have to learn value semantics and mutating funcs) and uses `@State` and `@Binding` property wrappers that allow value types behave like reference types, a mind bender I know but you really have to put the effort in here. If you give up and use view model objects then you have failed to grasp SwiftUI and you will lose all of the magic of its dependency tracking and efficient View struct hierarchy updates (the magical body method called only when needed). I recommend watching the WWDC20 SwiftUI videos to learn it, starting with the [introduction](https://developer.apple.com/videos/play/wwdc2020/10119/).

e.g.

```
import SwiftUI

struct ContentView: View {
    var body: some View {
        HStack {
            ShowTextEditor()
        }
    }
}

struct ShowTextEditor: View {
    @State var config = EditorConfig()
    
    var body: some View {
        VStack {
            Text(config.text)
            Button(action: show) {
                Text("Edit Text")
            }
        }
        .sheet(isPresented: $config.isShowing,
               onDismiss: didDismiss) {
            EditorView(config: $config)
        }
        
    }

    func show() {
        config.show() // you could pass in initial text here
    }
    
    func didDismiss() {
        // Handle the dismissing action.
    }
}


struct EditorConfig {
    var text = ""
    var isShowing = false
    
    mutating func show() {
        //text = initialText
        isShowing = true
    }
}

struct EditorView: View {
    @Binding var config: EditorConfig
    
    var body: some View {
        VStack {
            Text("Editor View").font(.title)
            TextField("Edit this text", text: $config.text)
                .padding()
        }
    }
}
```

**Comment by pauljohanneskraft** [comment]
Hey @malhal 

I'm totally aware of these constructs, including `@State` and `@Binding`. However, there is definitely reasons to use MVVM in certain situations depending on what your app is about and what you value most in app development. As I have pointed out [in this article](https://quickbirdstudios.com/blog/swiftui-architecture-redux-mvvm/), the Model-View architecture (as you describe it here) has its upsides in development speed and reduced code overhead, but lacks in testability, separation of concerns and ultimately maintainability. 

This library is intended for users of SwiftUI that value maintainability and testability over development speed and handling it "the default Apple way". With the property wrappers `@ObservedObject`, `@EnvironmentObject` and the addition of `@StateObject` in iOS 14, we also get the magic of only calling the body when needed. [You can learn more about this in this WWDC session.](https://developer.apple.com/videos/play/wwdc2020/10040/)

**Comment by malhal** [comment]
I took a look at the article and I think the fundamental flaw in your understanding is “SwiftUI recreates a View’s subviews every time the state changes.” The SwiftUI View struct is not a View rendered on screen in the sense of MVC or MVVM. There is absolutely no issue with View structs re-recreated in stack memory by the body method when data is changed this is super fast and is then diffed usually resulting in very minor changes to views on screen, and the View structs are thrown away instantly. If you put this data in objects in heap memory you are just recreating all the problems of traditional MVC. Please please please learn SwiftUI again before sharing anymore SwiftUI view model projects I believe it is very damaging to the community.

@StateObject is designed for loader or fetchers that require to be tied to view lifecycle and can also be the object in the App struct that holds the model struct.

**Comment by pauljohanneskraft** [comment]
I did not specify the recreation of views as an actual issue, just as a difference between SwiftUI and UIKit. SwiftUI views are sometimes stored in the heap as well (by the way), for example when you capture them in closures (for example in an `onAppear` view modifier).

Using only `@State` and `@Binding` in views looks like a great opportunity and way of programming user interface at first, but once your app gets more and more complex, you will either bloat your views with business logic, use property wrappers everywhere for everything (while they will simply "hide" the same complexity we are handling here) or create some form of object to encapsulate your business logic in.

Similar to the difference between MVC and MVVM in UIKit, we want to get rid of the business logic from the view layer and move it into its own layer. This way, a view's responsibility is only displaying information and triggering actions, but not the actual implementation of these actions and setting state itself.

Just curious: Which problems of MVC do you mean here specifically? There are definitely a few.

What do you actually dislike about MVVM in SwiftUI other than that it is not "the Apple way"? It works perfectly (i.e. it only updates the body when needed), creates modular architectures and makes it very intuitive for some developers.

**Comment by malhal** [comment]
Regarding "we want to get rid of the business logic from the view layer and move it into it's own layer." - the point I'm trying to make is SwiftUI View structs are not the view layer in the traditional sense, it is already "it's own layer", a view data layer that Apple created for us so we don't have to worry about this problem anymore. Logic can be functions in the View struct or moved into your own structs with mutating funcs, as you can see the beginnings of in the EditorConfig struct from my example above. With `@State` and mutating funcs Apple gave you what you liked about view model objects. With View's body tracking what `@State` vars change, the body recomputes are reduced, and the View structs are diffed to calculate what changes to UIKit or AppKit views are required reducing further, so Apple gave you the Redux style reducing you liked. They've done it all for us, there is no need to build an architecture that wraps SwiftUI trying to solve the same problems in an old/safer/more comfortable way of thinking. [Data Flow Through SwiftUI WWDC 2019](https://developer.apple.com/videos/play/wwdc2019/226/?time=868) explains why SwiftUI does this, although doesn't explain how the magic like the dependency tracking and reducing works. 

Views in SwiftUI cannot possibly get bloated like view controllers because of how they are designed to work. If someone uses them wrong then yes it is possible, I see a-lot of devs name their View structs as like DetailView, which is wrong, the name should not be like a view controller. A SwiftUI View should first be designed by only including the data that View struct needs to do its job, which is the data referenced by the body method. If there is a var not essential then it should not be in that struct because then the List's rows will be recomputed unnecessarily. E.g. if you have a View body that declares List and a Button (that toggles state), then when the var is toggled it would also recalculate the entire List rows again. The thing the button does should be extracted to its own View struct only with an `@State` to the toggle var in there. Now when the var is changed only the View containing the Button's body is recomputed without recalculating all the List rows. In your architecture, because you have an object that has many vars not all used precisely by that View now your body is needlessly being recomputed any time any `@Published` var of that object changes or `willChange` is sent, thus you broke SwiftUI's dependency tracking.

As you can see by the above example SwiftUI Views are all about the view data. You could call them the view model if you like. As Apple say in the WWDC videos, View structs should be small and you should always ask yourself, what data does this View struct need to do its job? [Data Essentials WWDC 2021](https://developer.apple.com/videos/play/wwdc2020/10040/)

One tip I give devs for transitioning their thinking from MVC to SwiftUI is design your View struct hierarchy from bottom up, making View structs as small as possible, and make them Previewable too. The reason is if you design from top down you end up thinking like View Controller again and things go wrong.

**Comment by kkiermasz** [comment]
@malhal interesting point of view. But I am wondering how do you want to test code which follows your convention? Could you please provide an example of:
* fetching some data (only from a high-level perspective, like calling a service method, without any URLSession' types etc.)
* testing above use case

**Comment by yojkim** [comment]
@malhal 

> Regarding "we want to get rid of the business logic from the view layer and move it into it's own layer." - the point I'm trying to make is SwiftUI View structs are not the view layer in the traditional sense, it is already "it's own layer", a view data layer that Apple created for us so we don't have to worry about this problem anymore. Logic can be functions in the View struct or moved into your own structs with mutating funcs, as you can see the beginnings of in the EditorConfig struct from my example above. With `@State` and mutating funcs Apple gave you what you liked about view model objects. With View's body tracking what `@State` vars change, the body recomputes are reduced, and the View structs are diffed to calculate what changes to UIKit or AppKit views are required reducing further, so Apple gave you the Redux style reducing you liked. They've done it all for us, there is no need to build an architecture that wraps SwiftUI trying to solve the same problems in an old/safer/more comfortable way of thinking. [Data Flow Through SwiftUI WWDC 2019](https://developer.apple.com/videos/play/wwdc2019/226/?time=868) explains why SwiftUI does this, although doesn't explain how the magic like the dependency tracking and reducing works.
> 
> Views in SwiftUI cannot possibly get bloated like view controllers because of how they are designed to work. If someone uses them wrong then yes it is possible, I see a-lot of devs name their View structs as like DetailView, which is wrong, the name should not be like a view controller. A SwiftUI View should first be designed by only including the data that View struct needs to do its job, which is the data referenced by the body method. If there is a var not essential then it should not be in that struct because then the List's rows will be recomputed unnecessarily. E.g. if you have a View body that declares List and a Button (that toggles state), then when the var is toggled it would also recalculate the entire List rows again. The thing the button does should be extracted to its own View struct only with an `@State` to the toggle var in there. Now when the var is changed only the View containing the Button's body is recomputed without recalculating all the List rows. In your architecture, because you have an object that has many vars not all used precisely by that View now your body is needlessly being recomputed any time any `@Published` var of that object changes or `willChange` is sent, thus you broke SwiftUI's dependency tracking.
> 
> As you can see by the above example SwiftUI Views are all about the view data. You could call them the view model if you like. As Apple say in the WWDC videos, View structs should be small and you should always ask yourself, what data does this View struct need to do its job? [Data Essentials WWDC 2021](https://developer.apple.com/videos/play/wwdc2020/10040/)
> 
> One tip I give devs for transitioning their thinking from MVC to SwiftUI is design your View struct hierarchy from bottom up, making View structs as small as possible, and make them Previewable too. The reason is if you design from top down you end up thinking like View Controller again and things go wrong.

I am very interested in your opinion. 
But I also wonder how to write test code and fetch the data from network or core data... 🤔
