### ISSUE TITLE
Name of this repository means a D-word in russian

### ISSUE THREAD

**Issue by andrew-medvedev** [quickbirdstudios/XUI#3]
Just in case the name of this repo (XUI) is very similar to russian word "ХУЙ"(a dick)

**Comment by pauljohanneskraft** [comment]
Hey @andrew-medvedev ! Thank you for letting us know 😊 

Since the name is an acronym (X as prefix, UI as `User Interface`) and we do not use Cyrillic Script, we assume that it is clear that the name is not intended to have this meaning.
