### ISSUE TITLE
Cannot assign to property: 'viewModel' is a get-only property

### ISSUE THREAD

**Issue by savage7** [quickbirdstudios/XUI#5]
When I create a init method which sets the viewModel the compiler give me an error:
_Cannot assign to property: 'viewModel' is a get-only property_

```
 @Store var viewModel: RecipeListViewModel

 init(viewModel: RecipeListViewModel) {
    self.viewModel = viewModel
 }
```

Can this be fixed? 

I put my View into a separate framework to speed up previews. For this I have to create a public init method manually, since autogenerated inits are always internal.

**Comment by pauljohanneskraft** [comment]
Hey @savage7 !

Since we use the `@Store` property wrapper instead of a regular property, you will need to instantiate the wrapper instead of the property.

You can try the following code:

```swift
 @Store var viewModel: RecipeListViewModel

 init(viewModel: RecipeListViewModel) {
    self._viewModel = Store(wrappedValue: viewModel)
 }
```

**Comment by savage7** [comment]
Thank you for your help! That was a obvious one, when you see the answer :wink:
